# Generated by Django 5.1.1 on 2025-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('qr_code', models.BinaryField()),
            ],
        ),
    ]
